export const STALE_TIME: number = 5 * 60 * 1000
export const GC_TIME: number = 10 * 60 * 1000
export const DEFAULT_CURRENCY_SYMBOL = '₪' as const

export type Milliseconds = number
export type CurrencySymbol = typeof DEFAULT_CURRENCY_SYMBOL // "₪"

export interface PendingImage {
  taskId: number
  name: string
  filePath: string
}
export type PendingImages = PendingImage[]

export interface PendingTaskItem {
  task: Task
  newStatus: string
  partialStatus: string
}
export type PendingTasks = PendingTaskItem[]

export interface Task {
  _id: string
  taskDetails: TaskDetail[]
  assignedTo: AssignedTo
  taskType: string
  statusId: string
  typeId: string
  isArchived: boolean
  createdAt: ISODateString
  archivedAt: ISODateString | null
  lastUpdatedAt: ISODateString
  lastUpdatedBy: LastUpdatedBy
  executionStartDate: ISODateString
  executionEndDate: ISODateString
  form: TaskFormField[]
  taskId: number
  groupName: string
  favoriteTask: boolean
  newTaskUuid: string
  __v: number
  urgentTask: boolean
  _dateInfo: DateInfo
}

export type ISODateString = string

export interface TaskDetail {
  label: string
  showInTable: boolean
  order: number | null
  orderMobile: number | null
  inputType: string
  key: string
  format?: string
  value?: unknown
  fromDefaultProp?: boolean
}

export interface AssignedTo {
  agentName: string
  agentSub: string
  agentGroups: string
}

export interface LastUpdatedBy {
  userName: string
  userSub: string
  userGroups: string
}

export interface DateInfo {
  currItemDate: string
  currentDay: string
  taskCount: number
  sameDate: boolean
}

export interface TaskFormRules {
  required: boolean
  actions: string[]
}
export type TaskFormConditions = Record<string, string[]>

export interface TaskFormBase {
  key: string
  inputType: string
  note: string
  validation: string
  label: string
  description: string
  placeholder: string
  defaultValue: unknown
  value: unknown
  displayValue: string
  layout: string
  taskDetailKey: string | null
  autocompleteKey: string | null
  autocompleteTable: string | null
  captureMode: string[]
  itemLimit: number
  videoDurationLimit: number
  gallery: boolean
  conditions?: TaskFormConditions
  rules?: TaskFormRules
}

export interface TaskFormCheckboxes extends TaskFormBase {
  inputType: 'checkboxes'
  options: Record<string, string>
  value: string[]
}

export interface TaskFormCameraButton extends TaskFormBase {
  inputType: 'cameraButton'
  value: string[]
}

export interface TaskFormText extends TaskFormBase {
  inputType: 'text'
  value: string
}

export interface TaskFormButton extends TaskFormBase {
  inputType: 'button'
  value: ISODateString
}

export interface TaskFormDateTimeRegister extends TaskFormBase {
  inputType: 'dateTimeRegister'
  value: ISODateString
}

export type TaskFormField =
  | TaskFormCheckboxes
  | TaskFormCameraButton
  | TaskFormText
  | TaskFormButton
  | TaskFormDateTimeRegister
  | TaskFormBase

export const pendingTasks: PendingTasks = [
  {
    task: {
      _id: '689afd230b4421e6734e49b9',
      taskDetails: [
        {
          label: 'שם משלם',
          showInTable: true,
          order: 6,
          orderMobile: 5,
          inputType: 'string',
          key: 'payerName',
        },
        {
          label: 'עיר משלם',
          showInTable: true,
          order: 7,
          orderMobile: 4,
          inputType: 'string',
          key: 'payerCity',
        },
        {
          label: 'כתובת משלם',
          showInTable: true,
          order: 5,
          orderMobile: 3,
          inputType: 'string',
          key: 'payerStreet',
        },
        {
          label: 'תאריך יצירה',
          showInTable: true,
          order: 10,
          orderMobile: null,
          inputType: 'dateTime',
          key: 'createdAt',
          format: 'DD/MM/YYYY HH:mm',
          value: '2025-08-12T08:36:51.667Z',
          fromDefaultProp: true,
        },
        {
          label: 'מספר משלם',
          showInTable: true,
          order: 12,
          orderMobile: null,
          inputType: 'string',
          key: 'payerNumber',
        },
        {
          label: 'סכום צפוי נוכחי',
          showInTable: true,
          order: 20,
          orderMobile: null,
          inputType: 'currency',
          key: 'expAmountNow',
          format: '#,##0.## $',
        },
        {
          label: 'הוצאה קודמת',
          showInTable: true,
          order: 21,
          orderMobile: null,
          inputType: 'currency',
          key: 'expAmountPrev',
          format: '#,##0.## $',
        },
        {
          label: 'סה"כ',
          showInTable: true,
          order: 22,
          orderMobile: 8,
          inputType: 'currency',
          key: 'paymentAmount',
          format: '#,##0.## $',
        },
        {
          label: 'מספר עיקול',
          showInTable: true,
          order: 23,
          orderMobile: null,
          inputType: 'string',
          key: 'foreclosureId',
        },
        {
          label: 'תאריך יצירת ממשק',
          showInTable: true,
          order: 24,
          orderMobile: null,
          inputType: 'date',
          key: 'interfaceDateCreation',
        },
        {
          label: 'מספר דירה',
          showInTable: true,
          order: 25,
          orderMobile: null,
          inputType: 'string',
          key: 'payerAprt',
        },
        {
          label: 'מספר',
          showInTable: true,
          order: 26,
          orderMobile: null,
          inputType: 'string',
          key: 'payerHouse',
        },
        {
          label: 'תז משלם',
          showInTable: true,
          order: 27,
          orderMobile: 6,
          inputType: 'string',
          key: 'payerId',
        },
        {
          label: 'מסמך עיקול ברישום',
          showInTable: true,
          order: 29,
          orderMobile: null,
          inputType: 'string',
          key: 'docIkulRishum',
        },
        {
          label: 'סוג נכס',
          showInTable: true,
          order: 30,
          orderMobile: null,
          inputType: 'string',
          key: 'propertyType',
        },
        {
          label: 'מספר משימה',
          showInTable: true,
          order: 1,
          orderMobile: 1,
          inputType: 'string',
          key: 'taskId',
          value: 6259,
          fromDefaultProp: true,
        },
        {
          label: 'סטאטוס',
          showInTable: true,
          order: 2,
          orderMobile: 7,
          inputType: 'string',
          key: 'statusId',
          value: 'assigned',
          fromDefaultProp: true,
        },
        {
          label: 'שם סוכן',
          showInTable: true,
          order: 8,
          orderMobile: null,
          inputType: 'any',
          key: 'assignedTo',
          value: {
            id: '01c6617d-914f-4d6a-bf5b-07241c7651b6',
            value: 'Vincent Enriquez',
          },
          fromDefaultProp: true,
        },
        {
          label: 'כתובת הנכס',
          showInTable: true,
          order: 4,
          orderMobile: null,
          inputType: 'string',
          key: 'propertyAddress',
        },
        {
          label: 'כתובת לביצוע עיקול',
          showInTable: true,
          order: 14,
          orderMobile: 10,
          inputType: 'string',
          key: 'addressPerformingProcedure',
        },
        {
          label: 'הודעת עיקול שניה',
          showInTable: true,
          order: 15,
          orderMobile: null,
          inputType: 'string',
          key: 'docDrisha2Url',
        },
        {
          label: 'מספר רשות',
          showInTable: true,
          order: 16,
          orderMobile: null,
          inputType: 'string',
          key: 'authorityId',
        },
        {
          label: 'יתרה',
          showInTable: true,
          order: 17,
          orderMobile: 9,
          inputType: 'currency',
          key: 'balanceAmount',
          format: '# $',
        },
        {
          label: 'מספר מחלקה',
          showInTable: true,
          order: 18,
          orderMobile: null,
          inputType: 'string',
          key: 'departmentId',
        },
        {
          label: 'הודעת עיקול ראשונה',
          showInTable: true,
          order: 19,
          orderMobile: 30,
          inputType: 'string',
          key: 'docDrisha1Url',
        },
        {
          label: 'פרטי משימת עיקול ברישום #2',
          showInTable: true,
          order: 28,
          orderMobile: 16,
          inputType: 'string',
          key: 'doc_Application2',
          format: '',
        },
        {
          label: 'מסמכים שהתקבלו',
          showInTable: true,
          order: 32,
          orderMobile: null,
          inputType: 'dropdown',
          key: 'T10',
        },
        {
          label: 'סיבת בקשה',
          showInTable: true,
          order: 33,
          orderMobile: null,
          inputType: 'string',
          key: 'T11',
        },
        {
          label: 'פטור מתאריך',
          showInTable: true,
          order: 34,
          orderMobile: null,
          inputType: 'date',
          key: 'T12',
        },
        {
          label: 'עד תאריך',
          showInTable: true,
          order: 35,
          orderMobile: null,
          inputType: 'date',
          key: 'T13',
        },
        {
          label: 'מספר נכס',
          showInTable: true,
          order: 36,
          orderMobile: null,
          inputType: 'number',
          key: 'T15',
        },
        {
          label: 'תיאור/הערות',
          showInTable: true,
          order: 37,
          orderMobile: null,
          inputType: 'string',
          key: 'T16',
        },
        {
          label: 'פרטי משימת עיקול ברישום',
          showInTable: true,
          order: 38,
          orderMobile: 15,
          inputType: 'string',
          key: 'doc_Application1',
          format: '',
        },
        {
          label: 'זמן סיום משימה',
          showInTable: true,
          order: 11,
          orderMobile: null,
          inputType: 'dateTime',
          key: 'taskEndTime',
          format: 'DD/MM/YYYY HH:mm',
        },
        {
          label: 'תאריך אחרון לביצוע',
          showInTable: true,
          order: 13,
          orderMobile: null,
          inputType: 'date',
          key: 'executionEndDate',
          value: '2025-08-13T00:00:00.000Z',
          fromDefaultProp: true,
        },
        {
          label: 'סוג משימה',
          showInTable: true,
          order: 3,
          orderMobile: 2,
          inputType: 'string',
          key: 'taskType',
          value: 'Register Test',
          fromDefaultProp: true,
        },
        {
          key: 'groupName',
          value: 'agam::da2a6f61-35fe-40f3-af24-2af77889019a',
          label: 'שם רשות / מחלקה',
          showInTable: true,
          order: 9,
          orderMobile: null,
          inputType: 'string',
          fromDefaultProp: true,
        },
        {
          label: 'מספר נכסים',
          showInTable: true,
          order: 31,
          orderMobile: null,
          inputType: 'string',
          key: 'qtyOfProperties',
        },
        {
          label: 'מספר נכס2',
          showInTable: true,
          order: null,
          orderMobile: 100,
          inputType: 'number',
          key: 'propertynum',
          format: '',
        },
      ],
      assignedTo: {
        agentName: 'Vincent Enriquez',
        agentSub: '01c6617d-914f-4d6a-bf5b-07241c7651b6',
        agentGroups: 'agent',
      },
      taskType: 'Register Test',
      statusId: 'pending',
      typeId: '',
      isArchived: false,
      createdAt: '2025-08-12T08:36:51.667Z',
      archivedAt: null,
      lastUpdatedAt: '2025-08-12T08:38:21.551Z',
      lastUpdatedBy: {
        userName: 'אלמוני',
        userSub: '9d3a07e9-9cbe-4ac3-85e4-a5010e1a6529',
        userGroups: 'admin',
      },
      executionStartDate: '2025-08-12T08:38:21.111Z',
      executionEndDate: '2025-08-13T00:00:00.000Z',
      form: [
        {
          key: 'registeredDateTask',
          inputType: 'dateTimeRegister',
          note: '',
          validation: '',
          label: 'Register task',
          description: '',
          placeholder: '',
          defaultValue: '',
          value: '2025-08-12T08:42:37.823Z',
          displayValue: '',
          layout: 'vertical',
          taskDetailKey: null,
          autocompleteKey: null,
          autocompleteTable: null,
          captureMode: ['camera'],
          itemLimit: 5,
          videoDurationLimit: 120,
          gallery: true,
          rules: {
            required: true,
            actions: ['startTask'],
          },
        },
        {
          key: 'address',
          inputType: 'text',
          note: '',
          validation: '',
          label: 'Address',
          description: '',
          placeholder: '',
          defaultValue: '',
          value: '6',
          displayValue: '',
          layout: 'vertical',
          taskDetailKey: null,
          autocompleteKey: null,
          autocompleteTable: null,
          captureMode: ['camera'],
          itemLimit: 5,
          videoDurationLimit: 120,
          gallery: true,
          conditions: {
            registeredDateTask: ['!null'],
          },
          rules: {
            required: true,
            actions: [],
          },
        },
        {
          key: 'transmitForm',
          inputType: 'checkboxes',
          note: '',
          validation: '',
          label: 'Status button to check',
          description: '',
          placeholder: '',
          options: {
            None: 'None',
            Close: 'Close',
          },
          defaultValue: [],
          value: ['None', 'Close'],
          displayValue: '',
          layout: 'vertical',
          taskDetailKey: null,
          autocompleteKey: null,
          autocompleteTable: null,
          captureMode: ['camera'],
          itemLimit: 5,
          videoDurationLimit: 120,
          gallery: true,
          conditions: {
            address: ['!null'],
          },
          rules: {
            required: true,
            actions: [],
          },
        },
        {
          key: 'proof',
          inputType: 'cameraButton',
          note: '',
          validation: '',
          label: 'Proof',
          description: '',
          placeholder: '',
          defaultValue: '',
          value: [
            'rn_image_picker_lib_temp_8a5e58cb-9ba7-431e-aae0-417a2fbee184.png',
            'rn_image_picker_lib_temp_ed28642f-4248-4b92-acb3-54cbf570caf6.png',
            'rn_image_picker_lib_temp_c7ec992c-a99a-4edc-9ecf-1592cb49286b.png',
            'rn_image_picker_lib_temp_754a3b4b-13ac-4ad1-bad6-9c9db943449d.png',
            'rn_image_picker_lib_temp_f55f4615-7d2f-4c78-a130-1f186c48e5d2.png',
            'rn_image_picker_lib_temp_52337be6-06dc-4f1c-aaac-abdf9c51e6c1.png',
          ],
          displayValue: '',
          layout: 'vertical',
          taskDetailKey: null,
          autocompleteKey: null,
          autocompleteTable: null,
          captureMode: ['camera', 'video'],
          itemLimit: 10,
          videoDurationLimit: 120,
          gallery: true,
          conditions: {
            transmitForm: ['!null'],
          },
          rules: {
            required: true,
            actions: [],
          },
        },
        {
          key: 'submitForm',
          inputType: 'button',
          note: '',
          validation: '',
          label: 'Submit',
          description: '',
          placeholder: '',
          defaultValue: '',
          value: '2025-08-12T08:45:08.879Z',
          displayValue: '',
          layout: 'vertical',
          taskDetailKey: null,
          autocompleteKey: null,
          autocompleteTable: null,
          captureMode: ['camera'],
          itemLimit: 5,
          videoDurationLimit: 120,
          gallery: true,
          conditions: {
            proof: ['!null'],
          },
          rules: {
            required: true,
            actions: ['transmitDone'],
          },
        },
      ],
      taskId: 6259,
      groupName: 'agam::da2a6f61-35fe-40f3-af24-2af77889019a',
      favoriteTask: false,
      newTaskUuid: 'f8f35dfe-0833-412b-a8e2-c426580a4668',
      __v: 0,
      urgentTask: false,
      _dateInfo: {
        currItemDate: '13.8.25',
        currentDay: 'Wednesday',
        taskCount: 1,
        sameDate: false,
      },
    },
    newStatus: 'done',
    partialStatus: 'pending',
  },

  {
    task: {
      _id: '689afd230b4421e6734e49b9',
      taskDetails: [
        {
          label: 'שם משלם',
          showInTable: true,
          order: 6,
          orderMobile: 5,
          inputType: 'string',
          key: 'payerName',
        },
        {
          label: 'עיר משלם',
          showInTable: true,
          order: 7,
          orderMobile: 4,
          inputType: 'string',
          key: 'payerCity',
        },
        {
          label: 'כתובת משלם',
          showInTable: true,
          order: 5,
          orderMobile: 3,
          inputType: 'string',
          key: 'payerStreet',
        },
        {
          label: 'תאריך יצירה',
          showInTable: true,
          order: 10,
          orderMobile: null,
          inputType: 'dateTime',
          key: 'createdAt',
          format: 'DD/MM/YYYY HH:mm',
          value: '2025-08-12T08:36:51.667Z',
          fromDefaultProp: true,
        },
        {
          label: 'מספר משלם',
          showInTable: true,
          order: 12,
          orderMobile: null,
          inputType: 'string',
          key: 'payerNumber',
        },
        {
          label: 'סכום צפוי נוכחי',
          showInTable: true,
          order: 20,
          orderMobile: null,
          inputType: 'currency',
          key: 'expAmountNow',
          format: '#,##0.## $',
        },
        {
          label: 'הוצאה קודמת',
          showInTable: true,
          order: 21,
          orderMobile: null,
          inputType: 'currency',
          key: 'expAmountPrev',
          format: '#,##0.## $',
        },
        {
          label: 'סה"כ',
          showInTable: true,
          order: 22,
          orderMobile: 8,
          inputType: 'currency',
          key: 'paymentAmount',
          format: '#,##0.## $',
        },
        {
          label: 'מספר עיקול',
          showInTable: true,
          order: 23,
          orderMobile: null,
          inputType: 'string',
          key: 'foreclosureId',
        },
        {
          label: 'תאריך יצירת ממשק',
          showInTable: true,
          order: 24,
          orderMobile: null,
          inputType: 'date',
          key: 'interfaceDateCreation',
        },
        {
          label: 'מספר דירה',
          showInTable: true,
          order: 25,
          orderMobile: null,
          inputType: 'string',
          key: 'payerAprt',
        },
        {
          label: 'מספר',
          showInTable: true,
          order: 26,
          orderMobile: null,
          inputType: 'string',
          key: 'payerHouse',
        },
        {
          label: 'תז משלם',
          showInTable: true,
          order: 27,
          orderMobile: 6,
          inputType: 'string',
          key: 'payerId',
        },
        {
          label: 'מסמך עיקול ברישום',
          showInTable: true,
          order: 29,
          orderMobile: null,
          inputType: 'string',
          key: 'docIkulRishum',
        },
        {
          label: 'סוג נכס',
          showInTable: true,
          order: 30,
          orderMobile: null,
          inputType: 'string',
          key: 'propertyType',
        },
        {
          label: 'מספר משימה',
          showInTable: true,
          order: 1,
          orderMobile: 1,
          inputType: 'string',
          key: 'taskId',
          value: 6259,
          fromDefaultProp: true,
        },
        {
          label: 'סטאטוס',
          showInTable: true,
          order: 2,
          orderMobile: 7,
          inputType: 'string',
          key: 'statusId',
          value: 'assigned',
          fromDefaultProp: true,
        },
        {
          label: 'שם סוכן',
          showInTable: true,
          order: 8,
          orderMobile: null,
          inputType: 'any',
          key: 'assignedTo',
          value: {
            id: '01c6617d-914f-4d6a-bf5b-07241c7651b6',
            value: 'Vincent Enriquez',
          },
          fromDefaultProp: true,
        },
        {
          label: 'כתובת הנכס',
          showInTable: true,
          order: 4,
          orderMobile: null,
          inputType: 'string',
          key: 'propertyAddress',
        },
        {
          label: 'כתובת לביצוע עיקול',
          showInTable: true,
          order: 14,
          orderMobile: 10,
          inputType: 'string',
          key: 'addressPerformingProcedure',
        },
        {
          label: 'הודעת עיקול שניה',
          showInTable: true,
          order: 15,
          orderMobile: null,
          inputType: 'string',
          key: 'docDrisha2Url',
        },
        {
          label: 'מספר רשות',
          showInTable: true,
          order: 16,
          orderMobile: null,
          inputType: 'string',
          key: 'authorityId',
        },
        {
          label: 'יתרה',
          showInTable: true,
          order: 17,
          orderMobile: 9,
          inputType: 'currency',
          key: 'balanceAmount',
          format: '# $',
        },
        {
          label: 'מספר מחלקה',
          showInTable: true,
          order: 18,
          orderMobile: null,
          inputType: 'string',
          key: 'departmentId',
        },
        {
          label: 'הודעת עיקול ראשונה',
          showInTable: true,
          order: 19,
          orderMobile: 30,
          inputType: 'string',
          key: 'docDrisha1Url',
        },
        {
          label: 'פרטי משימת עיקול ברישום #2',
          showInTable: true,
          order: 28,
          orderMobile: 16,
          inputType: 'string',
          key: 'doc_Application2',
          format: '',
        },
        {
          label: 'מסמכים שהתקבלו',
          showInTable: true,
          order: 32,
          orderMobile: null,
          inputType: 'dropdown',
          key: 'T10',
        },
        {
          label: 'סיבת בקשה',
          showInTable: true,
          order: 33,
          orderMobile: null,
          inputType: 'string',
          key: 'T11',
        },
        {
          label: 'פטור מתאריך',
          showInTable: true,
          order: 34,
          orderMobile: null,
          inputType: 'date',
          key: 'T12',
        },
        {
          label: 'עד תאריך',
          showInTable: true,
          order: 35,
          orderMobile: null,
          inputType: 'date',
          key: 'T13',
        },
        {
          label: 'מספר נכס',
          showInTable: true,
          order: 36,
          orderMobile: null,
          inputType: 'number',
          key: 'T15',
        },
        {
          label: 'תיאור/הערות',
          showInTable: true,
          order: 37,
          orderMobile: null,
          inputType: 'string',
          key: 'T16',
        },
        {
          label: 'פרטי משימת עיקול ברישום',
          showInTable: true,
          order: 38,
          orderMobile: 15,
          inputType: 'string',
          key: 'doc_Application1',
          format: '',
        },
        {
          label: 'זמן סיום משימה',
          showInTable: true,
          order: 11,
          orderMobile: null,
          inputType: 'dateTime',
          key: 'taskEndTime',
          format: 'DD/MM/YYYY HH:mm',
        },
        {
          label: 'תאריך אחרון לביצוע',
          showInTable: true,
          order: 13,
          orderMobile: null,
          inputType: 'date',
          key: 'executionEndDate',
          value: '2025-08-13T00:00:00.000Z',
          fromDefaultProp: true,
        },
        {
          label: 'סוג משימה',
          showInTable: true,
          order: 3,
          orderMobile: 2,
          inputType: 'string',
          key: 'taskType',
          value: 'Register Test',
          fromDefaultProp: true,
        },
        {
          key: 'groupName',
          value: 'agam::da2a6f61-35fe-40f3-af24-2af77889019a',
          label: 'שם רשות / מחלקה',
          showInTable: true,
          order: 9,
          orderMobile: null,
          inputType: 'string',
          fromDefaultProp: true,
        },
        {
          label: 'מספר נכסים',
          showInTable: true,
          order: 31,
          orderMobile: null,
          inputType: 'string',
          key: 'qtyOfProperties',
        },
        {
          label: 'מספר נכס2',
          showInTable: true,
          order: null,
          orderMobile: 100,
          inputType: 'number',
          key: 'propertynum',
          format: '',
        },
      ],
      assignedTo: {
        agentName: 'Vincent Enriquez',
        agentSub: '01c6617d-914f-4d6a-bf5b-07241c7651b6',
        agentGroups: 'agent',
      },
      taskType: 'Register Test',
      statusId: 'pending',
      typeId: '',
      isArchived: false,
      createdAt: '2025-08-12T08:36:51.667Z',
      archivedAt: null,
      lastUpdatedAt: '2025-08-12T08:38:21.551Z',
      lastUpdatedBy: {
        userName: 'אלמוני',
        userSub: '9d3a07e9-9cbe-4ac3-85e4-a5010e1a6529',
        userGroups: 'admin',
      },
      executionStartDate: '2025-08-12T08:38:21.111Z',
      executionEndDate: '2025-08-13T00:00:00.000Z',
      form: [
        {
          key: 'registeredDateTask',
          inputType: 'dateTimeRegister',
          note: '',
          validation: '',
          label: 'Register task',
          description: '',
          placeholder: '',
          defaultValue: '',
          value: '2025-08-12T08:42:37.823Z',
          displayValue: '',
          layout: 'vertical',
          taskDetailKey: null,
          autocompleteKey: null,
          autocompleteTable: null,
          captureMode: ['camera'],
          itemLimit: 5,
          videoDurationLimit: 120,
          gallery: true,
          rules: {
            required: true,
            actions: ['startTask'],
          },
        },
        {
          key: 'address',
          inputType: 'text',
          note: '',
          validation: '',
          label: 'Address',
          description: '',
          placeholder: '',
          defaultValue: '',
          value: '6',
          displayValue: '',
          layout: 'vertical',
          taskDetailKey: null,
          autocompleteKey: null,
          autocompleteTable: null,
          captureMode: ['camera'],
          itemLimit: 5,
          videoDurationLimit: 120,
          gallery: true,
          conditions: {
            registeredDateTask: ['!null'],
          },
          rules: {
            required: true,
            actions: [],
          },
        },
        {
          key: 'transmitForm',
          inputType: 'checkboxes',
          note: '',
          validation: '',
          label: 'Status button to check',
          description: '',
          placeholder: '',
          options: {
            None: 'None',
            Close: 'Close',
          },
          defaultValue: [],
          value: ['None', 'Close'],
          displayValue: '',
          layout: 'vertical',
          taskDetailKey: null,
          autocompleteKey: null,
          autocompleteTable: null,
          captureMode: ['camera'],
          itemLimit: 5,
          videoDurationLimit: 120,
          gallery: true,
          conditions: {
            address: ['!null'],
          },
          rules: {
            required: true,
            actions: [],
          },
        },
        {
          key: 'proof',
          inputType: 'cameraButton',
          note: '',
          validation: '',
          label: 'Proof',
          description: '',
          placeholder: '',
          defaultValue: '',
          value: [
            'rn_image_picker_lib_temp_8a5e58cb-9ba7-431e-aae0-417a2fbee184.png',
            'rn_image_picker_lib_temp_ed28642f-4248-4b92-acb3-54cbf570caf6.png',
            'rn_image_picker_lib_temp_c7ec992c-a99a-4edc-9ecf-1592cb49286b.png',
            'rn_image_picker_lib_temp_754a3b4b-13ac-4ad1-bad6-9c9db943449d.png',
            'rn_image_picker_lib_temp_f55f4615-7d2f-4c78-a130-1f186c48e5d2.png',
            'rn_image_picker_lib_temp_52337be6-06dc-4f1c-aaac-abdf9c51e6c1.png',
          ],
          displayValue: '',
          layout: 'vertical',
          taskDetailKey: null,
          autocompleteKey: null,
          autocompleteTable: null,
          captureMode: ['camera', 'video'],
          itemLimit: 10,
          videoDurationLimit: 120,
          gallery: true,
          conditions: {
            transmitForm: ['!null'],
          },
          rules: {
            required: true,
            actions: [],
          },
        },
        {
          key: 'submitForm',
          inputType: 'button',
          note: '',
          validation: '',
          label: 'Submit',
          description: '',
          placeholder: '',
          defaultValue: '',
          value: '2025-08-12T08:45:08.879Z',
          displayValue: '',
          layout: 'vertical',
          taskDetailKey: null,
          autocompleteKey: null,
          autocompleteTable: null,
          captureMode: ['camera'],
          itemLimit: 5,
          videoDurationLimit: 120,
          gallery: true,
          conditions: {
            proof: ['!null'],
          },
          rules: {
            required: true,
            actions: ['transmitDone'],
          },
        },
      ],
      taskId: 6261,
      groupName: 'agam::da2a6f61-35fe-40f3-af24-2af77889019a',
      favoriteTask: false,
      newTaskUuid: 'f8f35dfe-0833-412b-a8e2-c426580a4668',
      __v: 0,
      urgentTask: false,
      _dateInfo: {
        currItemDate: '13.8.25',
        currentDay: 'Wednesday',
        taskCount: 1,
        sameDate: false,
      },
    },
    newStatus: 'done',
    partialStatus: 'pending',
  },
  {
    task: {
      _id: '689afd230b4421e6734e49b9',
      taskDetails: [
        {
          label: 'שם משלם',
          showInTable: true,
          order: 6,
          orderMobile: 5,
          inputType: 'string',
          key: 'payerName',
        },
        {
          label: 'עיר משלם',
          showInTable: true,
          order: 7,
          orderMobile: 4,
          inputType: 'string',
          key: 'payerCity',
        },
        {
          label: 'כתובת משלם',
          showInTable: true,
          order: 5,
          orderMobile: 3,
          inputType: 'string',
          key: 'payerStreet',
        },
        {
          label: 'תאריך יצירה',
          showInTable: true,
          order: 10,
          orderMobile: null,
          inputType: 'dateTime',
          key: 'createdAt',
          format: 'DD/MM/YYYY HH:mm',
          value: '2025-08-12T08:36:51.667Z',
          fromDefaultProp: true,
        },
        {
          label: 'מספר משלם',
          showInTable: true,
          order: 12,
          orderMobile: null,
          inputType: 'string',
          key: 'payerNumber',
        },
        {
          label: 'סכום צפוי נוכחי',
          showInTable: true,
          order: 20,
          orderMobile: null,
          inputType: 'currency',
          key: 'expAmountNow',
          format: '#,##0.## $',
        },
        {
          label: 'הוצאה קודמת',
          showInTable: true,
          order: 21,
          orderMobile: null,
          inputType: 'currency',
          key: 'expAmountPrev',
          format: '#,##0.## $',
        },
        {
          label: 'סה"כ',
          showInTable: true,
          order: 22,
          orderMobile: 8,
          inputType: 'currency',
          key: 'paymentAmount',
          format: '#,##0.## $',
        },
        {
          label: 'מספר עיקול',
          showInTable: true,
          order: 23,
          orderMobile: null,
          inputType: 'string',
          key: 'foreclosureId',
        },
        {
          label: 'תאריך יצירת ממשק',
          showInTable: true,
          order: 24,
          orderMobile: null,
          inputType: 'date',
          key: 'interfaceDateCreation',
        },
        {
          label: 'מספר דירה',
          showInTable: true,
          order: 25,
          orderMobile: null,
          inputType: 'string',
          key: 'payerAprt',
        },
        {
          label: 'מספר',
          showInTable: true,
          order: 26,
          orderMobile: null,
          inputType: 'string',
          key: 'payerHouse',
        },
        {
          label: 'תז משלם',
          showInTable: true,
          order: 27,
          orderMobile: 6,
          inputType: 'string',
          key: 'payerId',
        },
        {
          label: 'מסמך עיקול ברישום',
          showInTable: true,
          order: 29,
          orderMobile: null,
          inputType: 'string',
          key: 'docIkulRishum',
        },
        {
          label: 'סוג נכס',
          showInTable: true,
          order: 30,
          orderMobile: null,
          inputType: 'string',
          key: 'propertyType',
        },
        {
          label: 'מספר משימה',
          showInTable: true,
          order: 1,
          orderMobile: 1,
          inputType: 'string',
          key: 'taskId',
          value: 6259,
          fromDefaultProp: true,
        },
        {
          label: 'סטאטוס',
          showInTable: true,
          order: 2,
          orderMobile: 7,
          inputType: 'string',
          key: 'statusId',
          value: 'assigned',
          fromDefaultProp: true,
        },
        {
          label: 'שם סוכן',
          showInTable: true,
          order: 8,
          orderMobile: null,
          inputType: 'any',
          key: 'assignedTo',
          value: {
            id: '01c6617d-914f-4d6a-bf5b-07241c7651b6',
            value: 'Vincent Enriquez',
          },
          fromDefaultProp: true,
        },
        {
          label: 'כתובת הנכס',
          showInTable: true,
          order: 4,
          orderMobile: null,
          inputType: 'string',
          key: 'propertyAddress',
        },
        {
          label: 'כתובת לביצוע עיקול',
          showInTable: true,
          order: 14,
          orderMobile: 10,
          inputType: 'string',
          key: 'addressPerformingProcedure',
        },
        {
          label: 'הודעת עיקול שניה',
          showInTable: true,
          order: 15,
          orderMobile: null,
          inputType: 'string',
          key: 'docDrisha2Url',
        },
        {
          label: 'מספר רשות',
          showInTable: true,
          order: 16,
          orderMobile: null,
          inputType: 'string',
          key: 'authorityId',
        },
        {
          label: 'יתרה',
          showInTable: true,
          order: 17,
          orderMobile: 9,
          inputType: 'currency',
          key: 'balanceAmount',
          format: '# $',
        },
        {
          label: 'מספר מחלקה',
          showInTable: true,
          order: 18,
          orderMobile: null,
          inputType: 'string',
          key: 'departmentId',
        },
        {
          label: 'הודעת עיקול ראשונה',
          showInTable: true,
          order: 19,
          orderMobile: 30,
          inputType: 'string',
          key: 'docDrisha1Url',
        },
        {
          label: 'פרטי משימת עיקול ברישום #2',
          showInTable: true,
          order: 28,
          orderMobile: 16,
          inputType: 'string',
          key: 'doc_Application2',
          format: '',
        },
        {
          label: 'מסמכים שהתקבלו',
          showInTable: true,
          order: 32,
          orderMobile: null,
          inputType: 'dropdown',
          key: 'T10',
        },
        {
          label: 'סיבת בקשה',
          showInTable: true,
          order: 33,
          orderMobile: null,
          inputType: 'string',
          key: 'T11',
        },
        {
          label: 'פטור מתאריך',
          showInTable: true,
          order: 34,
          orderMobile: null,
          inputType: 'date',
          key: 'T12',
        },
        {
          label: 'עד תאריך',
          showInTable: true,
          order: 35,
          orderMobile: null,
          inputType: 'date',
          key: 'T13',
        },
        {
          label: 'מספר נכס',
          showInTable: true,
          order: 36,
          orderMobile: null,
          inputType: 'number',
          key: 'T15',
        },
        {
          label: 'תיאור/הערות',
          showInTable: true,
          order: 37,
          orderMobile: null,
          inputType: 'string',
          key: 'T16',
        },
        {
          label: 'פרטי משימת עיקול ברישום',
          showInTable: true,
          order: 38,
          orderMobile: 15,
          inputType: 'string',
          key: 'doc_Application1',
          format: '',
        },
        {
          label: 'זמן סיום משימה',
          showInTable: true,
          order: 11,
          orderMobile: null,
          inputType: 'dateTime',
          key: 'taskEndTime',
          format: 'DD/MM/YYYY HH:mm',
        },
        {
          label: 'תאריך אחרון לביצוע',
          showInTable: true,
          order: 13,
          orderMobile: null,
          inputType: 'date',
          key: 'executionEndDate',
          value: '2025-08-13T00:00:00.000Z',
          fromDefaultProp: true,
        },
        {
          label: 'סוג משימה',
          showInTable: true,
          order: 3,
          orderMobile: 2,
          inputType: 'string',
          key: 'taskType',
          value: 'Register Test',
          fromDefaultProp: true,
        },
        {
          key: 'groupName',
          value: 'agam::da2a6f61-35fe-40f3-af24-2af77889019a',
          label: 'שם רשות / מחלקה',
          showInTable: true,
          order: 9,
          orderMobile: null,
          inputType: 'string',
          fromDefaultProp: true,
        },
        {
          label: 'מספר נכסים',
          showInTable: true,
          order: 31,
          orderMobile: null,
          inputType: 'string',
          key: 'qtyOfProperties',
        },
        {
          label: 'מספר נכס2',
          showInTable: true,
          order: null,
          orderMobile: 100,
          inputType: 'number',
          key: 'propertynum',
          format: '',
        },
      ],
      assignedTo: {
        agentName: 'Vincent Enriquez',
        agentSub: '01c6617d-914f-4d6a-bf5b-07241c7651b6',
        agentGroups: 'agent',
      },
      taskType: 'Register Test',
      statusId: 'pending',
      typeId: '',
      isArchived: false,
      createdAt: '2025-08-12T08:36:51.667Z',
      archivedAt: null,
      lastUpdatedAt: '2025-08-12T08:38:21.551Z',
      lastUpdatedBy: {
        userName: 'אלמוני',
        userSub: '9d3a07e9-9cbe-4ac3-85e4-a5010e1a6529',
        userGroups: 'admin',
      },
      executionStartDate: '2025-08-12T08:38:21.111Z',
      executionEndDate: '2025-08-13T00:00:00.000Z',
      form: [
        {
          key: 'registeredDateTask',
          inputType: 'dateTimeRegister',
          note: '',
          validation: '',
          label: 'Register task',
          description: '',
          placeholder: '',
          defaultValue: '',
          value: '2025-08-12T08:42:37.823Z',
          displayValue: '',
          layout: 'vertical',
          taskDetailKey: null,
          autocompleteKey: null,
          autocompleteTable: null,
          captureMode: ['camera'],
          itemLimit: 5,
          videoDurationLimit: 120,
          gallery: true,
          rules: {
            required: true,
            actions: ['startTask'],
          },
        },
        {
          key: 'address',
          inputType: 'text',
          note: '',
          validation: '',
          label: 'Address',
          description: '',
          placeholder: '',
          defaultValue: '',
          value: '6',
          displayValue: '',
          layout: 'vertical',
          taskDetailKey: null,
          autocompleteKey: null,
          autocompleteTable: null,
          captureMode: ['camera'],
          itemLimit: 5,
          videoDurationLimit: 120,
          gallery: true,
          conditions: {
            registeredDateTask: ['!null'],
          },
          rules: {
            required: true,
            actions: [],
          },
        },
        {
          key: 'transmitForm',
          inputType: 'checkboxes',
          note: '',
          validation: '',
          label: 'Status button to check',
          description: '',
          placeholder: '',
          options: {
            None: 'None',
            Close: 'Close',
          },
          defaultValue: [],
          value: ['None', 'Close'],
          displayValue: '',
          layout: 'vertical',
          taskDetailKey: null,
          autocompleteKey: null,
          autocompleteTable: null,
          captureMode: ['camera'],
          itemLimit: 5,
          videoDurationLimit: 120,
          gallery: true,
          conditions: {
            address: ['!null'],
          },
          rules: {
            required: true,
            actions: [],
          },
        },
        {
          key: 'proof',
          inputType: 'cameraButton',
          note: '',
          validation: '',
          label: 'Proof',
          description: '',
          placeholder: '',
          defaultValue: '',
          value: [
            'rn_image_picker_lib_temp_8a5e58cb-9ba7-431e-aae0-417a2fbee184.png',
            'rn_image_picker_lib_temp_ed28642f-4248-4b92-acb3-54cbf570caf6.png',
            'rn_image_picker_lib_temp_c7ec992c-a99a-4edc-9ecf-1592cb49286b.png',
            'rn_image_picker_lib_temp_754a3b4b-13ac-4ad1-bad6-9c9db943449d.png',
            'rn_image_picker_lib_temp_f55f4615-7d2f-4c78-a130-1f186c48e5d2.png',
            'rn_image_picker_lib_temp_52337be6-06dc-4f1c-aaac-abdf9c51e6c1.png',
          ],
          displayValue: '',
          layout: 'vertical',
          taskDetailKey: null,
          autocompleteKey: null,
          autocompleteTable: null,
          captureMode: ['camera', 'video'],
          itemLimit: 10,
          videoDurationLimit: 120,
          gallery: true,
          conditions: {
            transmitForm: ['!null'],
          },
          rules: {
            required: true,
            actions: [],
          },
        },
        {
          key: 'submitForm',
          inputType: 'button',
          note: '',
          validation: '',
          label: 'Submit',
          description: '',
          placeholder: '',
          defaultValue: '',
          value: '2025-08-12T08:45:08.879Z',
          displayValue: '',
          layout: 'vertical',
          taskDetailKey: null,
          autocompleteKey: null,
          autocompleteTable: null,
          captureMode: ['camera'],
          itemLimit: 5,
          videoDurationLimit: 120,
          gallery: true,
          conditions: {
            proof: ['!null'],
          },
          rules: {
            required: true,
            actions: ['transmitDone'],
          },
        },
      ],
      taskId: 6262,
      groupName: 'agam::da2a6f61-35fe-40f3-af24-2af77889019a',
      favoriteTask: false,
      newTaskUuid: 'f8f35dfe-0833-412b-a8e2-c426580a4668',
      __v: 0,
      urgentTask: false,
      _dateInfo: {
        currItemDate: '13.8.25',
        currentDay: 'Wednesday',
        taskCount: 1,
        sameDate: false,
      },
    },
    newStatus: 'done',
    partialStatus: 'pending',
  },
]

export const pendingImages: PendingImages = [
  {
    taskId: 6259,
    name: 'task/6259/rn_image_picker_lib_temp_38b50861-313b-4c99-9072-c85650aed34a.png',
    filePath:
      'file:///data/user/0/com.vincentenrqz.productmobilenew/cache/ImagePicker/409995d5-c44b-40a2-963c-c85650aed34a.jpeg',
  },
  {
    taskId: 6259,
    name: 'task/6259/rn_image_picker_lib_temp_5aaae884-845a-49e2-84bb-5f86d14c7afd.png',
    filePath:
      'file:///data/user/0/com.vincentenrqz.productmobilenew/cache/ImagePicker/409995d5-c44b-40a2-963c-4fbb-bc9d-e1e5cf0278ed.jpeg',
  },
  {
    taskId: 6259,
    name: 'task/6259/rn_image_picker_lib_temp_bd00e3db-5d57-4fbb-bc9d-e1e5cf0278ed.png',
    filePath: 'file:///invalid/path/to/image.jpeg',
  },
  {
    taskId: 6259,
    name: 'task/6259/409995d5-c44b-40a2-963c-cb2014e39d46.jpeg',
    filePath:
      'file:///data/user/0/com.vincentenrqz.productmobilenew/cache/ImagePicker/409995d5-c44b-40a2-963c-cb2014e39d46.jpeg',
  },
]
